---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-storage001
  labels:
    release: test
spec:
  capacity:
    storage: 5Gi
  storageClassName: nfs-standard
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.207
    path: "/sugardon02-storage/pv001"

---
# For nextcloud data dir
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-nextclouddata
  labels:
    release: test
spec:
  capacity:
    storage: 1Ti
  storageClassName: nfs-nextclouddata
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.20.207
    path: "/storage"
