---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-storage001
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-standard
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      release: test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-nextcloud-storage
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-nextcloud-storage
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      release: test
