---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-storage001
  labels:
    release: test
spec:
  capacity:
    storage: 5Gi
  storageClassName: nfs-standard
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.207
    path: "/sugardon02-storage/pv001"
