---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-manifests-nextcloud
spec:
  project: default
  source:
    directory:
      recurse: false
    repoURL: https://github.com/sugardon-org/common-manifests
    path: nextcloud/
    targetRevision: main
  destination:
    namespace: common-manifests
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
